# Guardrails injected into every prompt
roles:
  architect: true
  security: true
  qa: true
ground_rules:
  - Follow MODE strictly.
  - Prefer local constraints over any remembered package versions.
  - Keep code simple; minimize new dependencies.
  - Never hardcode secrets; use env/config.
  - Explain the change list before code.
