# Defines deliverables and guardrails per phase
phases:
  discovery:
    goals:
      - Identify unknowns and feasibility of key tech/techniques
      - Run spikes/prototypes to test limits
    out_of_scope:
      - Production code
      - Non-essential UI polish
    deliverables:
      - DISCOVERY.md (findings, risks, spike results)
      - Q&A checklist
  design:
    goals:
      - End-to-end POC that demonstrates business potential
      - Outline business engine components
    out_of_scope:
      - Full test coverage
      - Perf/security hardening
    deliverables:
      - DESIGN.md (arch, interfaces, diagrams)
      - POC README with run steps
  mvp:
    goals:
      - End-to-end app covering 2-10 use cases
      - Core business logic correct and extensible
    out_of_scope:
      - Production hardening
      - Full SLO/SLA
    deliverables:
      - MVP.md (scope, routes/features)
      - Minimal tests + demo script
  production:
    goals:
      - Harden for reliability, security, scale
      - Observability, CI/CD, migrations, docs
    out_of_scope:
      - Scope creep beyond approved backlog
    deliverables:
      - ADRs for risky changes
      - Expanded test suites and runbooks
